name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: angelomds42/kernel_build_action@main
        with:
          kernel-url: https://github.com/knyprjkt/android_kernel_xiaomi_spes
          kernel-dir: msm-4.19
          kernel-branch: reze
          config: vendor/spes-perf_defconfig
          arch: arm64
          aosp-clang: true
          android-version: 16
          aosp-clang-version: r547379
          anykernel3: true
          anykernel3-url: https://github.com/mrsrimar22/AnyKernel3
          depth: 1
